package model

import (
	"time"

	"gorm.io/gorm"
)

// MonitorData represents the monitoring data for a device
type MonitorData struct {
	gorm.Model
	DeviceID      uint           `gorm:"not null" json:"device_id"`
	Type          string         `gorm:"not null" json:"type"`
	IP            string         `gorm:"not null" json:"ip"`
	EARFCN        int            `json:"earfcn"`
	RSRP          float64        `json:"rsrp"`
	SNR           float64        `json:"snr"`
	Distance      float64        `json:"distance"`
	Timestamp     time.Time      `gorm:"not null" json:"timestamp"`
	CPUUsage      float64        `json:"cpu_usage"`
	MemoryUsage   float64        `json:"memory_usage"`
	DiskUsage     float64        `json:"disk_usage"`
	NetworkIn     float64        `json:"network_in"`
	NetworkOut    float64        `json:"network_out"`
	Temperature   float64        `json:"temperature"`
	SignalQuality float64        `json:"signal_quality"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`
}

// MonitorConfig represents the monitoring configuration for a device
type MonitorConfig struct {
	gorm.Model
	DeviceID         uint           `gorm:"not null" json:"device_id"`
	EnableMonitoring bool           `json:"enable_monitoring"`
	MonitorInterval  int            `json:"monitor_interval"`
	RetentionPeriod  int            `json:"retention_period"`
	AlertThresholds  string         `json:"alert_thresholds"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"index" json:"-"`
}

// MonitorAlert represents an alert generated by monitoring
type MonitorAlert struct {
	ID         uint       `json:"id" gorm:"primaryKey"`
	DeviceID   uint       `json:"device_id" gorm:"not null"`
	Type       string     `json:"type" gorm:"not null"`  // Type of alert (e.g., "high_cpu", "low_signal")
	Level      string     `json:"level" gorm:"not null"` // Alert level (e.g., "warning", "error", "critical")
	Message    string     `json:"message" gorm:"not null"`
	Value      float64    `json:"value"`
	Threshold  float64    `json:"threshold"`
	Status     string     `json:"status" gorm:"not null"` // Status of alert (e.g., "active", "acknowledged", "resolved")
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	ResolvedAt *time.Time `json:"resolved_at"`
}
