# 6680单板AT指令配置
board_type: "6680"
description: "6680模块AT指令集"
version: "2.0"

commands:
  # 网络状态相关命令
  get_net_state:
    at_command: "AT+NETSTATE?"
    description: "Get network state"
    response_format: "json"

  set_master_slave:
    at_command: "AT+MSMODE=%d"
    description: "Set master-slave mode"
    parameters:
      - name: "mode"
        type: "int"
        range: [0, 1]
        description: "0: Slave, 1: Master"

  # 安全相关命令
  set_encryption:
    at_command: "AT+ENC=%s"
    description: "Set encryption algorithm"
    parameters:
      - name: "algorithm"
        type: "string"
        values: ["AES128", "AES256", "DES"]
        description: "Encryption algorithm"

  # 无线相关命令
  set_frequency_band:
    at_command: "AT+BAND=%d"
    description: "Set frequency band"
    parameters:
      - name: "band"
        type: "int"
        values: [800, 1400, 2400]
        description: "Frequency band in MHz"

  # 接入状态
  get_access_state:
    at_command: "AT^DACS?"
    description: "获取接入状态"
    response_format: "text"

  set_access_state:
    at_command: "AT^DACS=%d"
    description: "设置接入状态上报"
    parameters:
      - name: "n"
        type: "int"
        values: [0, 1, 2]
        description: "0: 关闭, 1: 开启, 2: WEBUI上报"

  # 无线参数配置
  get_radio_params:
    at_command: "AT^DRPC?"
    description: "获取无线参数配置"
    response_format: "text"

  set_radio_params:
    at_command: "AT^DRPC=%d,%d,%s[,%d]"
    description: "设置无线参数"
    parameters:
      - name: "freq"
        type: "int"
        range: [24015, 24814]
        description: "频点频率(100KHz)"
      - name: "bandwidth"
        type: "int"
        values: [0, 1, 2, 3, 5]
        description: "带宽(0:1.4M, 1:3M, 2:5M, 3:10M, 5:20M)"
      - name: "power"
        type: "string"
        pattern: "^-?\\d+$"
        description: "发射功率(dBm)"
      - name: "cellid"
        type: "int"
        values: [0, 1]
        description: "小区ID(0:Pcell, 1:Scell)"

  # 无线参数存储
  get_radio_params_store:
    at_command: "AT^DRPS?"
    description: "获取存储的无线参数"
    response_format: "text"

  set_radio_params_store:
    at_command: "AT^DRPS=%d,%d,%s[,%d]"
    description: "存储无线参数"
    parameters:
      - name: "freq"
        type: "int"
        range: [24015, 24814]
        description: "频点频率(100KHz)"
      - name: "bandwidth"
        type: "int"
        values: [0, 1, 2, 3, 5]
        description: "带宽(0:1.4M, 1:3M, 2:5M, 3:10M, 5:20M)"
      - name: "power"
        type: "string"
        pattern: "^-?\\d+$"
        description: "发射功率(dBm)"
      - name: "cellid"
        type: "int"
        values: [0, 1]
        description: "小区ID(0:Pcell, 1:Scell)"

  # 从节点最大发射功率
  get_slave_max_tx_power:
    at_command: "AT^DSSMTP?"
    description: "获取从节点最大发射功率"
    response_format: "text"

  set_slave_max_tx_power:
    at_command: "AT^DSSMTP=%s[,%s]"
    description: "设置从节点最大发射功率"
    parameters:
      - name: "power"
        type: "string"
        pattern: "^-?\\d+$"
        description: "从节点pcell最大发射功率(dBm)"
      - name: "scell_power"
        type: "string"
        pattern: "^-?\\d+$"
        description: "从节点scell最大发射功率(dBm)"

  # 无线参数上报
  get_radio_param_report:
    at_command: "AT^DRPR?"
    description: "获取无线参数上报状态"
    response_format: "text"

  set_radio_param_report:
    at_command: "AT^DRPR=%d"
    description: "设置无线参数上报"
    parameters:
      - name: "n"
        type: "int"
        values: [0, 1, 2]
        description: "0:关闭, 1:开启, 2:WEBUI上报"