# 2.0版本星型单板AT指令配置
board_type: "2.0_star"
description: "2.0版本星型单板AT指令集"
version: "2.0"

commands:
  get_access_state:
    at_command: "AT^DACS?"
    description: "获取接入状态"
    response_format: "text"

  set_access_state:
    at_command: "AT^DACS=%d"
    description: "设置接入状态上报"
    parameters:
      - name: "n"
        type: "int"
        values: [0, 1, 2]
        description: "0: 关闭, 1: 开启, 2: WEBUI上报"

  get_radio_params:
    at_command: "AT^DRPC?"
    description: "获取无线参数配置"
    response_format: "text"

  set_radio_params:
    at_command: "AT^DRPC=%d,%d,%s,%d"
    description: "设置无线参数"
    parameters:
      - name: "freq"
        type: "int"
        description: "频点频率(100KHz)"
      - name: "bandwidth"
        type: "int"
        description: "带宽(0:1.4M, 1:3M, 2:5M, 3:10M, 4:15M, 5:20M)"
      - name: "power"
        type: "string"
        description: "发射功率(dBm), 范围-40到40"
      - name: "cellid"
        type: "int"
        description: "小区ID(0:主小区, 1:辅小区)"

  get_radio_params_store:
    at_command: "AT^DRPS?"
    description: "获取存储的无线参数"
    response_format: "text"

  set_radio_params_store:
    at_command: "AT^DRPS=%d,%d,%s,%d"
    description: "存储无线参数"
    parameters:
      - name: "freq"
        type: "int"
        description: "频点频率(100KHz)"
      - name: "bandwidth"
        type: "int"
        description: "带宽(0:1.4M, 1:3M, 2:5M, 3:10M, 4:15M, 5:20M)"
      - name: "power"
        type: "string"
        description: "发射功率(dBm), 范围-40到40"
      - name: "cellid"
        type: "int"
        description: "小区ID(0:主小区, 1:辅小区)"

  get_slave_max_tx_power:
    at_command: "AT^DSSMTP?"
    description: "获取从节点最大发射功率"
    response_format: "text"

  set_slave_max_tx_power:
    at_command: "AT^DSSMTP=%s,%s"
    description: "设置从节点最大发射功率"
    parameters:
      - name: "power"
        type: "string"
        description: "主小区最大发射功率(dBm), 范围-40到50"
      - name: "scell_power"
        type: "string"
        description: "辅小区最大发射功率(dBm), 范围-40到50"

  get_radio_param_report:
    at_command: "AT^DRPR?"
    description: "获取无线参数上报状态"
    response_format: "text"

  set_radio_param_report:
    at_command: "AT^DRPR=%d"
    description: "设置无线参数上报"
    parameters:
      - name: "n"
        type: "int"
        values: [0, 1, 2]
        description: "0:关闭, 1:开启, 2:WEBUI上报"

  get_all_radio_param_report:
    at_command: "AT^DAPR?"
    description: "获取所有接入节点无线参数上报状态"
    response_format: "text"

  set_all_radio_param_report:
    at_command: "AT^DAPR=%d"
    description: "设置所有接入节点无线参数上报"
    parameters:
      - name: "n"
        type: "int"
        values: [0, 1, 2]
        description: "0:关闭, 1:开启, 2:WEBUI上报"

  get_band_config:
    at_command: "AT^DAOCNDI?"
    description: "获取用户频段配置"
    response_format: "text"

  set_band_config:
    at_command: "AT^DAOCNDI=%s,%s"
    description: "设置用户频段配置"
    parameters:
      - name: "pcell_band_bitmap"
        type: "string"
        description: "主小区频段位图(十六进制)"
      - name: "scell_band_bitmap"
        type: "string"
        description: "辅小区频段位图(十六进制)"

  get_device_type:
    at_command: "AT^DDTC?"
    description: "获取设备类型配置"
    response_format: "text"

  set_device_type:
    at_command: "AT^DDTC=%d"
    description: "设置设备类型"
    parameters:
      - name: "type"
        type: "int"
        values: [1, 2]
        description: "1:中心节点, 2:接入节点"

  get_encryption_algorithm:
    at_command: "AT^DCIAC?"
    description: "获取加密算法配置"
    response_format: "text"

  set_encryption_algorithm:
    at_command: "AT^DCIAC=%d"
    description: "设置加密算法"
    parameters:
      - name: "algorithm"
        type: "int"
        values: [0, 1, 2, 3]
        description: "加密算法(0:无加密, 1:SNOW3G, 2:AES, 3:ZUC)"

  get_tdd_config:
    at_command: "AT^DSTC?"
    description: "获取TDD配置"
    response_format: "text"

  set_tdd_config:
    at_command: "AT^DSTC=%d"
    description: "设置TDD配置"
    parameters:
      - name: "config"
        type: "int"
        values: [0, 1, 2, 3]
        description: "TDD配置(0:2D3U, 1:3D2U, 2:4D1U, 3:1D4U)"

  get_frequency_hopping:
    at_command: "AT^DFHC?"
    description: "获取跳频控制状态"
    response_format: "text"

  set_frequency_hopping:
    at_command: "AT^DFHC=%d,%d"
    description: "设置跳频控制"
    parameters:
      - name: "n"
        type: "int"
        values: [0, 1]
        description: "0:关闭跳频, 1:开启跳频"
      - name: "HopInterval"
        type: "int"
        description: "跳频间隔(秒, 0-60)"

  get_network_config:
    at_command: "AT^NETIFCFG?"
    description: "获取网络接口配置"
    response_format: "text"

  set_network_config:
    at_command: "AT^NETIFCFG=%d,%s,%s,%s"
    description: "设置网络接口配置"
    parameters:
      - name: "type"
        type: "int"
        values: [2, 3, 4]
        description: "2:IP, 3:IP+MASK, 4:IP+MASK+GATEWAY"
      - name: "master_ip"
        type: "string"
        description: "主IP地址"
      - name: "sub_mask"
        type: "string"
        description: "子网掩码"
      - name: "gateway"
        type: "string"
        description: "网关地址"

  get_access_nodes:
    at_command: "AT^DIPAN"
    description: "获取所有接入节点IP地址列表"
    response_format: "text"

  set_powerctl:
    at_command: "AT^POWERCTL=%d"
    description: "模块重启"
    parameters:
      - name: "value"
        type: "int"
        values: [1]
        description: "1:重启"

  set_recovset:
    at_command: "AT^RECOVSET=%d"
    description: "恢复出厂设置"
    parameters:
      - name: "type"
        type: "int"
        values: [1]
        description: "1:恢复出厂设置" 